export const DUMMY_EXAM_DATA: Array<Exam> = [
  {
    id: "5f79b078-4c9a-4b27-9f32-58b10bfc49b1",
    title: "Matematika",
    examType: "Ujian Akhir",
    duration: "2 hours",
    totalQuestion: 5,
    questions: [
      {
        question: "Berapakah hasil dari 2 + 2?",
        options: ["3", "4", "5", "6", "7"],
        correctAnswer: "4",
      },
      {
        question: "Luas segitiga dengan alas 6 dan tinggi 8 adalah?",
        options: ["12", "24", "30", "36", "48"],
        correctAnswer: "24",
      },
      {
        question: "Apa hasil dari 5 x 9?",
        options: ["40", "45", "50", "55", "60"],
        correctAnswer: "45",
      },
      {
        question: "Akar kuadrat dari 64 adalah?",
        options: ["6", "7", "8", "9", "10"],
        correctAnswer: "8",
      },
      {
        question: "Jika a = 3 dan b = 4, berapakah nilai a^2 + b^2?",
        options: ["5", "9", "13", "15", "25"],
        correctAnswer: "25",
      },
    ],
    date: "2024-02-01",
    dueDate: "2024-02-15",
  },
  {
    id: "8c946c5f-679b-4a4f-9e48-28e5403a1e36",
    title: "Bahasa Inggris",
    examType: "Tugas Harian",
    duration: "1 hour",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa sinonim dari kata 'happy'?",
        options: ["Sad", "Joyful", "Angry", "Tired", "Excited"],
        correctAnswer: "Joyful",
      },
      {
        question: "Apa lawan kata dari 'fast'?",
        options: ["Slow", "Quick", "Rapid", "Swift", "Brisk"],
        correctAnswer: "Slow",
      },
      {
        question: "Apa arti dari kata 'beautiful' dalam bahasa Indonesia?",
        options: ["Jelek", "Indah", "Buruk", "Cantik", "Rusak"],
        correctAnswer: "Cantik",
      },
      {
        question: "Bagaimana cara mengeja kata 'environment' dengan benar?",
        options: [
          "Enviroment",
          "Environtment",
          "Enviromentt",
          "Environment",
          "Envayronment",
        ],
        correctAnswer: "Environment",
      },
      {
        question: "Apakah 'book' dalam bahasa Indonesia?",
        options: ["Meja", "Buku", "Kursi", "Pensil", "Lemari"],
        correctAnswer: "Buku",
      },
    ],
    date: "2024-02-05",
    dueDate: "2024-02-10",
  },
  {
    id: "9d57b0a5-6d86-4e46-8240-6c3bbec46b54",
    title: "Fisika",
    examType: "Tugas Harian",
    duration: "1 hour",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa rumus untuk menghitung gaya?",
        options: [
          "F = m * a",
          "E = m * c^2",
          "P = m * v",
          "F = m / a",
          "W = m * g",
        ],
        correctAnswer: "F = m * a",
      },
      {
        question: "Apa rumus untuk menghitung energi kinetik?",
        options: [
          "E = m * c^2",
          "K = 0.5 * m * v^2",
          "W = m * g * h",
          "P = m * v",
          "F = m * a",
        ],
        correctAnswer: "K = 0.5 * m * v^2",
      },
      {
        question: "Apa penyebab terjadinya gaya gravitasi?",
        options: [
          "Medan listrik",
          "Radiasi elektromagnetik",
          "Pergeseran lempeng tektonik",
          "Medan magnet",
          "Massa benda",
        ],
        correctAnswer: "Massa benda",
      },
      {
        question: "Apa rumus untuk menghitung usaha?",
        options: [
          "W = m * g * h",
          "E = m * c^2",
          "P = m * v",
          "F = m / a",
          "W = F * d",
        ],
        correctAnswer: "W = F * d",
      },
      {
        question:
          "Sebuah benda dilempar ke atas. Apa yang terjadi pada percepatannya?",
        options: [
          "Tetap",
          "Bertambah",
          "Berubah arah",
          "Nol",
          "Menjadi negatif",
        ],
        correctAnswer: "Menjadi negatif",
      },
    ],
    date: "2024-03-10",
    dueDate: "2024-03-20",
  },
  {
    id: "e42d9f39-4a3f-4f3b-9130-2e07c6f265d6",
    title: "Kimia",
    examType: "Ujian Akhir",
    duration: "2 hours",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa simbol kimia untuk unsur hidrogen?",
        options: ["Hg", "He", "H", "O", "N"],
        correctAnswer: "H",
      },
      {
        question: "Apa rumus kimia untuk air (H2O)?",
        options: ["CO2", "H2O", "CH4", "O2", "NH3"],
        correctAnswer: "H2O",
      },
      {
        question: "Apa jenis reaksi kimia yang melibatkan pelepasan panas?",
        options: [
          "Reaksi endotermis",
          "Reaksi eksotermis",
          "Reaksi redoks",
          "Reaksi dekomposisi",
          "Reaksi substitusi",
        ],
        correctAnswer: "Reaksi eksotermis",
      },
      {
        question: "Apa rumus kimia untuk gas oksigen?",
        options: ["CO2", "O2", "H2", "N2", "Cl2"],
        correctAnswer: "O2",
      },
      {
        question: "Berapa jumlah proton dalam inti atom karbon (C)?",
        options: ["4", "5", "6", "7", "8"],
        correctAnswer: "6",
      },
    ],
    date: "2024-03-15",
    dueDate: "2024-03-30",
  },
  {
    id: "bb0be78c-5b6d-4ed0-95cd-0d20f0fe4181",
    title: "Sejarah",
    examType: "Ujian Akhir",
    duration: "2 hours",
    totalQuestion: 5,
    questions: [
      {
        question: "Siapakah presiden pertama Indonesia?",
        options: [
          "Soekarno",
          "Soeharto",
          "Joko Widodo",
          "Abdurrahman Wahid",
          "Megawati Soekarnoputri",
        ],
        correctAnswer: "Soekarno",
      },
      {
        question: "Apa peristiwa yang terjadi pada 17 Agustus 1945?",
        options: [
          "Proklamasi Kemerdekaan",
          "Konferensi Asia Afrika",
          "Supersemar",
          "Revolusi Industri",
          "Tragedi G30S PKI",
        ],
        correctAnswer: "Proklamasi Kemerdekaan",
      },
      {
        question: "Kapan terjadinya Perang Dunia II?",
        options: [
          "1914-1918",
          "1939-1945",
          "1945-1950",
          "1950-1953",
          "1960-1965",
        ],
        correctAnswer: "1939-1945",
      },
      {
        question: "Apa penyebab terjadinya Perang Dingin?",
        options: [
          "Perebutan koloni",
          "Persaingan ideologi",
          "Sengketa wilayah",
          "Perebutan sumber daya alam",
          "Perang saudara",
        ],
        correctAnswer: "Persaingan ideologi",
      },
      {
        question: "Siapa tokoh Revolusi Industri di Inggris?",
        options: [
          "Karl Marx",
          "James Watt",
          "Thomas Edison",
          "Alexander Graham Bell",
          "Henry Ford",
        ],
        correctAnswer: "James Watt",
      },
    ],
    date: "2024-04-05",
    dueDate: "2024-04-20",
  },
  {
    id: "fda295ea-2ec8-4be9-91d5-e5a2f18ed67a",
    title: "Biologi",
    examType: "Tugas Harian",
    duration: "1 hour",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa fungsi mitokondria dalam sel?",
        options: [
          "Pengatur sel",
          "Pembentukan energi",
          "Pencernaan sel",
          "Pertahanan sel",
          "Peredaran darah",
        ],
        correctAnswer: "Pembentukan energi",
      },
      {
        question: "Apa perbedaan antara sel prokariotik dan eukariotik?",
        options: [
          "Ukuran",
          "Adanya inti sel",
          "Struktur membran",
          "Adanya organel sel",
          "Jumlah kromosom",
        ],
        correctAnswer: "Adanya inti sel",
      },
      {
        question: "Apa yang dimaksud dengan fotosintesis?",
        options: [
          "Pembentukan protein",
          "Pertukaran gas",
          "Penguraian senyawa",
          "Pengikatan energi matahari",
          "Pertumbuhan sel",
        ],
        correctAnswer: "Pengikatan energi matahari",
      },
      {
        question: "Berapa jumlah gigi pada manusia dewasa?",
        options: ["28", "32", "36", "40", "44"],
        correctAnswer: "32",
      },
      {
        question: "Apa yang menjadi fungsi DNA?",
        options: [
          "Pembentukan energi",
          "Pertahanan tubuh",
          "Pengatur pertumbuhan",
          "Pengkodean genetik",
          "Pertukaran zat",
        ],
        correctAnswer: "Pengkodean genetik",
      },
    ],
    date: "2024-04-10",
    dueDate: "2024-04-15",
  },
  {
    id: "f7e9d03e-35b4-4ac5-a34c-087ce2f74bc1",
    title: "Seni Musik",
    examType: "Ujian Akhir",
    duration: "2 hours",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa jenis alat musik gesek?",
        options: ["Gitar", "Piano", "Biola", "Flute", "Drum"],
        correctAnswer: "Biola",
      },
      {
        question: "Siapa komponis terkenal dari era Klasik?",
        options: ["Beethoven", "Mozart", "Bach", "Chopin", "Vivaldi"],
        correctAnswer: "Mozart",
      },
      {
        question: "Apa yang dimaksud dengan not balok?",
        options: [
          "Sistem penulisan nada",
          "Instrumen musik",
          "Skala musik",
          "Irama musik",
          "Suku not",
        ],
        correctAnswer: "Sistem penulisan nada",
      },
      {
        question: "Apa alat musik tiup yang terbuat dari logam?",
        options: ["Saxophone", "Clarinet", "Flute", "Trombone", "Trumpet"],
        correctAnswer: "Trumpet",
      },
      {
        question: "Apa yang dimaksud dengan tempo dalam musik?",
        options: [
          "Ketinggian nada",
          "Kecepatan irama",
          "Durasi not",
          "Jarak antar nada",
          "Dinamika musik",
        ],
        correctAnswer: "Kecepatan irama",
      },
    ],
    date: "2024-04-15",
    dueDate: "2024-04-30",
  },
  {
    id: "1a683cf6-4907-4e2b-8ed8-6ab65c327bd4",
    title: "Bahasa Indonesia",
    examType: "Tugas Harian",
    duration: "1 hour",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa jenis kata 'berlari'?",
        options: [
          "Kata Kerja",
          "Kata Benda",
          "Kata Sifat",
          "Kata Hubung",
          "Kata Seru",
        ],
        correctAnswer: "Kata Kerja",
      },
      {
        question: "Apa sinonim dari kata 'bersemangat'?",
        options: ["Malas", "Lesu", "Berat", "Ceria", "Riang"],
        correctAnswer: "Ceria",
      },
      {
        question: "Apa lawan kata dari 'jauh'?",
        options: ["Dekat", "Cepat", "Lambat", "Sedikit", "Lebar"],
        correctAnswer: "Dekat",
      },
      {
        question: "Apa fungsi dari tanda baca koma (,)?",
        options: [
          "Menandai akhir kalimat",
          "Memisahkan kata benda",
          "Memisahkan kalimat",
          "Menandai awal kalimat",
          "Menandai akhir paragraf",
        ],
        correctAnswer: "Memisahkan kalimat",
      },
      {
        question: "Apa makna dari ungkapan 'seperti kera mendapat bunga'?",
        options: [
          "Tidak tahu diri",
          "Senang sekali",
          "Dapat hadiah",
          "Berkembang biak",
          "Tidak suka bunga",
        ],
        correctAnswer: "Tidak tahu diri",
      },
    ],
    date: "2024-05-05",
    dueDate: "2024-05-15",
  },
  {
    id: "5fc6b156-8567-4aa0-bd7b-06e21898e4a3",
    title: "Teknologi Informasi",
    examType: "Ujian Akhir",
    duration: "2 hours",
    totalQuestion: 5,
    questions: [
      {
        question: "Apa kepanjangan dari HTML?",
        options: [
          "Hyper Transfer Markup Language",
          "Hyper Text Markup Language",
          "High Transfer Markup Language",
          "Hyperlink Text Markup Language",
          "High Text Markup Language",
        ],
        correctAnswer: "Hyper Text Markup Language",
      },
      {
        question: "Apa fungsi dari CSS dalam pengembangan web?",
        options: [
          "Mengatur tata letak",
          "Mengumpulkan data",
          "Menyimpan data",
          "Menganalisis data",
          "Memproses data",
        ],
        correctAnswer: "Mengatur tata letak",
      },
      {
        question: "Apa yang dimaksud dengan 'backend' dalam pengembangan web?",
        options: [
          "Bagian depan website",
          "Struktur halaman web",
          "Database dan server",
          "Gaya tata letak",
          "Bahasa pemrograman",
        ],
        correctAnswer: "Database dan server",
      },
      {
        question: "Apa peran dari SQL dalam pengembangan aplikasi database?",
        options: [
          "Menyusun tata letak",
          "Bahasa pemrograman",
          "Mengatur tata letak",
          "Mengelola database",
          "Menampilkan gambar",
        ],
        correctAnswer: "Mengelola database",
      },
      {
        question: "Apa yang dimaksud dengan 'API'?",
        options: [
          "Antarmuka Pengguna",
          "Akses Pribadi Internet",
          "Antarmuka Bahasa Pemrograman",
          "Aplikasi Pemrograman Internet",
          "Antarmuka Perangkat Keras",
        ],
        correctAnswer: "Antarmuka Pemrograman Internet",
      },
    ],
    date: "2024-05-10",
    dueDate: "2024-05-25",
  },
];
