import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import classNames from 'classnames'
import ThemeRegistry from '@/themes/ThemeRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body id="tailwind-root" className={classNames('',inter.className)}>
      <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
        </body>
    </html>
  )
}
